FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY ./apps/models/deepfake_detection/requirements.txt .

RUN pip install -r requirements.txt

COPY ./apps/models/deepfake_detection .

RUN mkdir -p model_checkpoints videos && \
    chmod 755 videos

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]