name: Build and Deploy to Docker Hub & VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Debug
      run: |
        echo "Docker username is correctly set: ${{ secrets.DOCKER_USERNAME != '' }}"
        echo "Docker password is correctly set: ${{ secrets.DOCKER_PASSWORD != '' }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build model and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.model
        push: true
        tags: asistiwari96/trufake-model:latest
        build-args: |
          MODEL_TOKEN_SECRET=${{ secrets.MODEL_TOKEN_SECRET }}

    - name: Build web and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.web
        push: true
        tags: asistiwari96/trufake-web:latest
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          MODEL_TOKEN_SECRET=${{ secrets.MODEL_TOKEN_SECRET }}
          NEXT_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_KEY }}
          NEXT_PUBLIC_URL_ENDPOINT=${{ secrets.NEXT_PUBLIC_URL_ENDPOINT }}
          PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker stop trufake-model || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker rm trufake-model || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker stop trufake-web || true
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker rm trufake-web || true

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker pull asistiwari96/trufake-model:latest
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker pull asistiwari96/trufake-web:latest


          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker run -d --name trufake-model \
            -e MODEL_TOKEN_SECRET=${{ secrets.MODEL_TOKEN_SECRET }} \
            -p 8000:8000 --restart always \
            asistiwari96/trufake-model:latest


          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker run -d --name trufake-web \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            -e MODEL_TOKEN_SECRET=${{ secrets.MODEL_TOKEN_SECRET }} \
            -e NEXT_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_KEY }} \
            -e NEXT_PUBLIC_URL_ENDPOINT=${{ secrets.NEXT_PUBLIC_URL_ENDPOINT }} \
            -e PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
            -p 3010:3010 --restart always \
            asistiwari96/trufake-web:latest

          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker image prune -f